### PR TITLE
added device JohnnyFiveTemperaturePressure 

### PR DESCRIPTION
**Pull request by kanedo**
I added a new device JohnnyFiveTemperaturePressure to support sensors like the `ms5611`.

The implementation is very similar to `JohnnyFiveTemperatureHumidity`.
I opted to use `hPa` instead of jonny-fives native `kPa` since I think its much more common in meteorologic data reporting

### CODE REVIEW

**Comment by mwittig** [comment]
Thank you very much for your contribution! One comment about commit https://github.com/mwittig/pimatic-johnny-five/pull/44/commits/05fe2db6ec837e20a7b9c763b9e4e3425038326f: I think it is not required to call emit directly as @_setTemperature and @_base.setAttribute() already take care of this.

**Review by mwittig — COMMENTED** [review]
I think it is not required to call emit directly as @_setTemperature and @_base.setAttribute() already take care of this.

**Comment by kanedo** [comment]
@mwittig Yes, I noticed that. Hence I reverted the changes in [05fe2db](https://github.com/mwittig/pimatic-johnny-five/pull/44/commits/05fe2db6ec837e20a7b9c763b9e4e3425038326f)

**Comment by mwittig** [comment]
Great. Thanks!

**Pull request merged**
